repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        name: Lint with Ruff
      - id: ruff-format
        name: Check formatting with Ruff

  - repo: local
    hooks:
      - id: ty
        name: Type check with ty
        entry: uv run ty check src/matpublib src/utils
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.11
    hooks:
      - id: uv-lock
        name: Update uv.lock file

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.11
    hooks:
      - id: uv-export
        name: Export requirements.txt