repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        name: Lint with Ruff
      - id: ruff-format
        name: Check formatting with Ruff

  - repo: local
    hooks:
      - id: pyright
        name: Type check with Pyright
        entry: uv run pyright
        language: system
        types: [python]
        pass_filenames: false
  # Pyright using remote repo hook
  # - repo: https://github.com/RobertCraigie/pyright-python
  #   rev: v1.1.398
  #   hooks:
  #     - id: pyright
  #       name: Type check with Pyright

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.11
    hooks:
      - id: uv-lock
        name: Update uv.lock file

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.11
    hooks:
      - id: uv-export
        name: Export requirements.txt