stages:
  create_figures:
    cmd: python src/produce_figures.py --params params.yaml
    deps:
    - data/Males.csv
    params:
    - data_etl.external_data_path
    - figure_manager.figures_dir
    - figure_manager.paper_size
    - figure_manager.file_ext
    - figure_manager.use_latex
    - plotter.verbose
    outs:
    - outputs/figures/three_small_plots.pdf
    - outputs/figures/three_small_plots_subplot_2.pdf 
    - outputs/figures/three_small_plots_subplot_1.pdf 
    - outputs/figures/three_small_plots_subplot_3.pdf 
    - outputs/figures/two_std_dev_plots_subplot_1.pdf 
    - outputs/figures/two_std_dev_plots_subplot_2.pdf 
    - outputs/figures/two_std_dev_plots.pdf
metrics:
  - metrics.json