name: Report
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      discussions: write
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libkrb5-dev yq imagemagick

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set up CML
        uses: iterative/setup-cml@v1

      - name: Create output
        run: uv run dvc repro

      - name: Get file extension and convert PDF if needed
        id: get_ext
        run: |
          FILE_EXT=$(yq '.figure_manager.file_ext' params.yaml)

          if [[ "$FILE_EXT" == '".pdf"' ]]; then
            mogrify -format jpg outputs/figures/three_small_plots.pdf
            mogrify -format jpg outputs/figures/two_std_dev_plots.pdf
            echo "FILE_EXT=.jpg" >> $GITHUB_OUTPUT
          else
            echo "FILE_EXT=$FILE_EXT" >> $GITHUB_OUTPUT
          fi

      - name: Create report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Parameters" > report.md
          uv run dvc metrics show --md >> report.md

          echo "# Main Plot" >> report.md
          echo "![Main Plot failed to display](./outputs/figures/three_small_plots${{ steps.get_ext.outputs.FILE_EXT }} \"Main plot\")" >> report.md

          echo "# Standard Deviation Plot" >> report.md
          echo "![Standard Deviation Plot failed to display](./outputs/figures/two_std_dev_plots${{ steps.get_ext.outputs.FILE_EXT }} \"Std. plot\")" >> report.md

          cml comment create report.md
