name: Report
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      discussions: write
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libkrb5-dev imagemagick
          wget https://github.com/mikefarah/yq/releases/download/v4.13.4/yq_linux_amd64 -O /usr/bin/yq 
          chmod +x /usr/bin/yq

      - name: Conditionally update file extension in params.yaml
        run: |
          # Use yq to modify params.yaml in-place (-i)
          # This command selects the .figure_manager.file_ext field,
          # checks if its value is exactly ".pdf", and if true, assigns ".png" to it.
          # If the value is not ".pdf", it does nothing to that field.
          # NOTE: This assumes a 'yq' compatible with the 'eval' command and this syntax (like mikefarah/yq v4+).
          # The version installed via apt might vary. If this fails, alternative methods exist (see below).
          yq eval '(.figure_manager.file_ext | select(. == ".pdf")) = ".png"' -i params.yaml

          echo "--- params.yaml after potential modification ---"
          cat params.yaml
          echo "---------------------------------------------"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set up CML
        uses: iterative/setup-cml@v1

      - name: Create output
        run: uv run dvc repro

      - name: Get file extension and convert PDF if needed
        id: get_ext
        run: |
          FILE_EXT=$(yq '.figure_manager.file_ext' params.yaml)

          if [[ "$FILE_EXT" == '".pdf"' ]]; then
            mogrify -format png outputs/figures/three_small_plots.pdf
            mogrify -format png outputs/figures/two_std_dev_plots.pdf
            echo "FILE_EXT=.png" >> $GITHUB_OUTPUT
          else
            echo "FILE_EXT=$FILE_EXT" >> $GITHUB_OUTPUT
          fi

      - name: Create report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Parameters" > report.md
          uv run dvc metrics show --md >> report.md

          echo "# Main Plot" >> report.md
          echo "![Main Plot failed to display](./outputs/figures/three_small_plots${{ steps.get_ext.outputs.FILE_EXT }} \"Main plot\")" >> report.md

          echo "# Standard Deviation Plot" >> report.md
          echo "![Standard Deviation Plot failed to display](./outputs/figures/two_std_dev_plots${{ steps.get_ext.outputs.FILE_EXT }} \"Std. plot\")" >> report.md

          cml comment create report.md
