name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Kerberos libraries
        run: sudo apt-get update && sudo apt-get install -y libkrb5-dev

      - name: Set up CML
        uses: iterative/setup-cml@v1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create figures
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro
          dvc metrics show --md > report.md
          echo '![](./outputs/figures/three_small_plots.png "Main plot")' >> report.md
          echo '![](./outputs/figures/two_std_dev_plots.png "Std. plot")' >> report.md
          cml comment create report.md
